<?php

/**
 * PluginSettingTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Setting');
    }

    /**
     * PluginSettingTable::get()
     *
     * @param mixed $name
     * @return
     */
    public static function get($name)
    {
        $setting = self::getInstance()->findOneBySettingName($name);
        if ($setting) {
            return $setting->getText();
        }

        return null;
    }

    /**
     * PluginSettingTable::set()
     *
     * @param mixed $name
     * @param mixed $text
     */
    public static function set($name, $text)
    {
        $setting = self::getInstance()->findOneBySettingName($name);
        if (!$setting) {
            $setting = new Setting();
            $setting->setSettingName($name);
        }
        $setting->setText($text);
        $setting->save();
    }

    public static function del($name)
    {
        self::getInstance()
            ->createQuery('s')
            ->delete()
            ->where('s.setting_name = ?', $name)
            ->execute();
    }
}