Setting:
  actAs:
    Timestampable:
  columns:
    id:
      primary: true
      unsigned: true
      type: integer
      notnull: true
      autoincrement: true
    setting_name:
      type: string(32)
      notnull: true
    text:
      type: string(512)
  indexes:
    IX_plugin_setting_table_1:
      fields: [setting_name]
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
